### ISSUE TITLE
jtopo的怎么启动呢

### ISSUE THREAD

**Issue by galary** [NLRX-WJC/Vue-Components-Library#2]
jtopo的怎么启动呢

**Comment by NLRX-WJC** [comment]
安装好依赖后，直接npm run dev就可以了呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: galary <notifications@github.com&gt;
发送时间: 2019年12月2日 19:26
收件人: NLRX-WJC/Vue-Components-Library <Vue-Components-Library@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[NLRX-WJC/Vue-Components-Library] jtopo的怎么启动呢 (#2)




jtopo的怎么启动呢

**Comment by galary** [comment]
依赖安装不了啊

**Comment by NLRX-WJC** [comment]
依赖安装不了是啥情况？npm install不行？？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: galary <notifications@github.com&gt;
发送时间: 2019年12月2日 19:48
收件人: NLRX-WJC/Vue-Components-Library <Vue-Components-Library@noreply.github.com&gt;
抄送: 难凉热血 <1292695701@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[NLRX-WJC/Vue-Components-Library] jtopo的怎么启动呢 (#2)
