### ISSUE TITLE
sideBar组件：折叠菜单之后文字不隐藏的问题

### ISSUE THREAD

**Issue by hocko333** [NLRX-WJC/Vue-Components-Library#3]
你好，我使用了sideBar组件，在折叠菜单之后，文字不会自动隐藏，我搜了解决方案，说是要用vue-fragment.js 的fragment标签来代替sideBarItem里面的外层div标签，但还是没有解决问题。
![image](https://user-images.githubusercontent.com/45919606/70064297-432edd80-1624-11ea-8f1d-9a9978db1439.png)
![image](https://user-images.githubusercontent.com/45919606/70064388-69ed1400-1624-11ea-97df-53f023589a3b.png)

**Comment by NLRX-WJC** [comment]
我记得我写的这个菜单组件只是递归显示多级菜单，好像没有折叠的功能呀

**Comment by hocko333** [comment]
> 我记得我写的这个菜单组件只是递归显示多级菜单，好像没有折叠的功能呀

您好，我想的是您这个是基于el-menu封装的嘛，而el-menu的collapse属性为true则可以折叠，但是现在折叠之后文字不隐藏，这让我有点苦恼
